### PR TITLE
Fix rendering of message about unsupported output type

### LINKED ISSUE #808: Rendering of unsupported output not working
If a trace server back-end returns a unknown provider type, then the `theia-trace-extension` used render a message `Not implemented yet`. This is not working anymore. Instead the following error occurs:
```
Uncaught TypeError TypeError: Cannot read properties of null (reading 'optionsDropdownOpen')
    at showOptionsMenu (./theia-trace-extension/packages/react-components/src/components/abstract-output-component.tsx:154:29)
    at renderTitleBar (./theia-trace-extension/packages/react-components/src/components/abstract-output-component.tsx:106:19)
    at render (./theia-trace-extension/packages/react-components/src/components/abstract-output-component.tsx:89:23)
    at finishClassComponent (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:17160:1)
    at updateClassComponent (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:17110:1)
    at beginWork (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:18620:1)
    at callCallback (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:188:1)
    at invokeGuardedCallbackDev (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:237:1)
    at invokeGuardedCallback (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:292:1)
    at beginWork$1 (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:23203:1)
    at performUnitOfWork (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:22157:1)
    at workLoopSync (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:22130:1)
    at performSyncWorkOnRoot (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:21756:1)
    at <anonymous> (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:11089:1)
    at unstable_runWithPriority (./theia-trace-extension/node_modules/scheduler/cjs/scheduler.development.js:653:1)
    at runWithPriority$1 (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:11039:1)
    at flushSyncCallbackQueueImpl (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:11084:1)
    at flushSyncCallbackQueue (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:11072:1)
    at scheduleUpdateOnFiber (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:21199:1)
    at updateContainer (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:24373:1)
    at legacyRenderSubtreeIntoContainer (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:24774:1)
    at render (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:24840:1)
    at onUpdateRequest (./theia-trace-extension/node_modules/@theia/core/src/browser/widgets/react-widget.tsx:42:18)
    at __webpack_modules__.../../node_modules/@phosphor/widgets/lib/widget.js.Widget.processMessage (./theia-trace-extension/node_modules/@phosphor/widgets/lib/widget.js:492:1)
    at invokeHandler (./theia-trace-extension/node_modules/@phosphor/messaging/lib/index.js:436:1)
    at sendMessage (./theia-trace-extension/node_modules/@phosphor/messaging/lib/index.js:172:1)
    at runMessageLoop (./theia-trace-extension/node_modules/@phosphor/messaging/lib/index.js:486:1)
    --- requestAnimationFrame ---
    at enqueueMessage (./theia-trace-extension/node_modules/@phosphor/messaging/lib/index.js:455:1)
    at postMessage (./theia-trace-extension/node_modules/@phosphor/messaging/lib/index.js:223:1)
    at __webpack_modules__.../../node_modules/@phosphor/widgets/lib/widget.js.Widget.update (./theia-trace-extension/node_modules/@phosphor/widgets/lib/widget.js:354:1)
    at doHandleOutputAddedSignal (./theia-trace-extension/theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx:368:22)
    --- await ---
    at TraceViewerWidget.onOutputAdded (./theia-trace-extension/theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx:66:88)
    at emit (./theia-trace-extension/node_modules/events/events.js:153:1)
    at fireOutputAddedSignal (./theia-trace-extension/packages/base/src/signals/signal-manager.ts:89:14)
    at doHandleOutputClicked (./theia-trace-extension/packages/react-components/src/trace-explorer/trace-explorer-views-widget.tsx:63:29)
    at ReactAvailableViewsWidget.handleOutputClicked (./theia-trace-extension/packages/react-components/src/trace-explorer/trace-explorer-views-widget.tsx:58:88)
    at doHandleOutputClicked (./theia-trace-extension/packages/react-components/src/components/utils/available-views-component.tsx:129:20)
    at AvailableViewsComponent.handleOutputClicked (./theia-trace-extension/packages/react-components/src/components/utils/available-views-component.tsx:27:89)
    at callCallback (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:188:1)
    at invokeGuardedCallbackDev (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:237:1)
    at invokeGuardedCallback (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:292:1)
    at invokeGuardedCallbackAndCatchFirstError (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:306:1)
    at executeDispatch (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:389:1)
    at executeDispatchesInOrder (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:414:1)
    at executeDispatchesAndRelease (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:3278:1)
    at executeDispatchesAndReleaseTopLevel (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:3287:1)
    at forEachAccumulated (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:3259:1)
    at runEventsInBatch (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:3304:1)
    at runExtractedPluginEventsInBatch (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:3514:1)
    at handleTopLevel (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:3558:1)
    at batchedEventUpdates$1 (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:21871:1)
    at batchedEventUpdates (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:795:1)
    at dispatchEventForLegacyPluginEventSystem (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:3568:1)
    at attemptToDispatchEvent (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:4267:1)
    at dispatchEvent (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:4189:1)
    at unstable_runWithPriority (./theia-trace-extension/node_modules/scheduler/cjs/scheduler.development.js:653:1)
    at runWithPriority$1 (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:11039:1)
    at discreteUpdates$1 (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:21887:1)
    at discreteUpdates (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:806:1)
    at dispatchDiscreteEvent (./theia-trace-extension/node_modules/react-dom/cjs/react-dom.development.js:4168:1)
root ERROR The above error occurred in the <NullOutputComponent> component:
    in NullOutputComponent (created by TraceContextComponent)
    in Resizable (created by GridItem)
    in DraggableCore (created by GridItem)
    in GridItem (created by ReactGridLayout)
    in div (created by ReactGridLayout)
    in ReactGridLayout (created by ResponsiveReactGridLayout)
    in ResponsiveReactGridLayout (created by WidthProvider)
    in WidthProvider (created by TraceContextComponent)
    in div (created by TraceContextComponent)
    in div (created by TraceContextComponent)
    in div (created by TraceContextComponent)
    in TraceContextComponent
    in div

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
./theia-trace-extension/node_modules/@theia/core/src/common/logger-protocol.ts:112
root ERROR TypeError: Cannot read properties of null (reading 'optionsDropdownOpen')
    at NullOutputComponent.showOptionsMenu (http://localhost:3000/node_modules_moment_locale_sync_recursive_-theia-extensions_viewer-prototype_lib_browser_trac-4eb71b.bundle.js:1284:24)
    at NullOutputComponent.renderTitleBar (http://localhost:3000/node_modules_moment_locale_sync_recursive_-theia-extensions_viewer-prototype_lib_browser_trac-4eb71b.bundle.js:1253:18)
    at NullOutputComponent.render (http://localhost:3000/node_modules_moment_locale_sync_recursive_-theia-extensions_viewer-prototype_lib_browser_trac-4eb71b.bundle.js:1243:293)
    at finishClassComponent (http://localhost:3000/bundle.js:120025:31)
    at updateClassComponent (http://localhost:3000/bundle.js:119975:24)
    at beginWork (http://localhost:3000/bundle.js:121485:16)
    at HTMLUnknownElement.callCallback (http://localhost:3000/bundle.js:103053:14)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/bundle.js:103102:16)
    at invokeGuardedCallback (http://localhost:3000/bundle.js:103157:31)
    at beginWork$1 (http://localhost:3000/bundle.js:126068:7)
```

### PR DESCRIPTION
**Pull request by bhufmann**
Fixes #808

Note: To test change the Trace Compass server back-end to return an unknown provider type in an output descriptor. This is how it will look like:

image

Signed-off-by: Bernd Hufmann <bernd.hufmann@ericsson.com>

### CODE REVIEW

**Review by marco-miller — COMMENTED** [review]
When I try to verify this PR, I'm unable to hit the breakpoints after forcing `responseType` in `renderGridLayout` (`trace-context-component.tsx`) to the default `NullOutputComponent` case. I then only get an empty Trace tab window without the expected message, in both color themes (light or dark).

I get the same result if renaming that type to an unknown one on Incubator's `trace-server` side (`ProviderType`'s). And strangely enough, with the current latest `master` version of that server, upon opening some views, I systematically hit breakpoints in `SegmentStore{Scatter,Table}DataProviderFactory`'s `getDescriptors`.

`Events Table` and `Histogram` (and the new default `Overview`) are the views I've been testing with so far. The trace I happened to use here is [github.com/dorsal-lab/OTF2_testcases](https://github.com/dorsal-lab/OTF2_testcases/tree/main/traces)'s `limited_bandwith` one.

I've been testing a cherry-picked version of this PR onto current latest `master` of this repo. This looks like a trivial cherry-pick anyway.

**Comment by bhufmann** [comment]
> When I try to verify this PR, I'm unable to hit the breakpoints after forcing `responseType` in `renderGridLayout` (`trace-context-component.tsx`) to the default `NullOutputComponent` case. I then only get an empty Trace tab window without the expected message, in both color themes (light or dark).

I was able to reproduce what you observed. The `NullOutputComponent` is created but its `renderMainArea` not called because in the base class method `renderMainOutputContainer` there is a check for `this.state.outputStatus` and it's not set in this case which causes a `TypeError`. I'll fix it.

**Review by marco-miller — CHANGES_REQUESTED** [review]
LGTM now; thanks. Just this note for me, the resulting message doesn't show fully if Overview is used as the view, AFAIK. One needs to manually expand the view window so the message becomes readable. This is not the case for other larger views. But WDYT?

**Comment by bhufmann** [comment]
> LGTM now; thanks. Just this note for me, the resulting message doesn't show fully if Overview is used as the view, AFAIK. One needs to manually expand the view window so the message becomes readable. This is not the case for other larger views. But WDYT?

I'm not sure if this could actually happen with a custom trace server. But, let me see if I can fix it.

**Review by marco-miller — APPROVED** [review]
LGTM enough then at this stage; thanks!

**Pull request merged**
