### PR TITLE
Add tooltip when hovering over trace in opened traces view

### LINKED ISSUE #897: Traces with same name can't be distinguished in open traces view
The list of traces in a trace set (a.k.a experiment) can't be distinguished if they have the same name. Also, it's not possible to know where the traces are located in the file system. 

image

The trace path should be shown as hover tooltip (for example).

### PR DESCRIPTION
**Pull request by bhufmann**
Fixes #897

Signed-off-by: Bernd Hufmann <bernd.hufmann@ericsson.com>

### CODE REVIEW

**Comment by hoangphamEclipse** [comment]
Thank you for the PR. I tried the code and the tooltip only worked when I hover over the line that starts with `>` (the second line). I think we should make it work for the whole div (the whole blue rectangle in the screenshot below) - except for the `Remove trace` icon. This is more user-friendly because intuitively not all users will know where to hover exactly. What do you think?

  image

**Comment by bhufmann** [comment]
> Thank you for the PR. I tried the code and the tooltip only worked when I hover over the line that starts with `>` (the second line). I think we should make it work for the whole div (the whole blue rectangle in the screenshot below) - except for the `Remove trace` icon. This is more user-friendly because intuitively not all users will know where to hover exactly. What do you think?
> 
> image

There might be multiple trace under the trace set and the hover text should be per trace.

**Comment by hoangphamEclipse** [comment]
True, I forgot about that scenario.

**Review by hoangphamEclipse — APPROVED** [review]
LGTM

**Pull request merged**
