### PR TITLE
README: Add cdt cloud demo link

### PR DESCRIPTION
**Pull request by ebugden**
@MatthewKhouzam recently added a video that shows how to try the trace viewer via the CDT cloud live demo. I thought it could be relevant to add this information to the repo readme as well.

Phrasing and content edits welcome!

### CODE REVIEW

**Comment by ebugden** [comment]
Signoff fixed!

I also just signed the contributor license agreement (screenshot below) with my efficios address so the test should pass now. I couldn't see how to re-run the check manually.

image

**Comment by ebugden** [comment]
Just confirming that according to the ECA Validator I now do have a valid ECA signed (green square in screenshot below). The test didn't pass at time of submission because I hadn't yet signed.

image

**Review by MatthewKhouzam — APPROVED** [review]

**Comment by ebugden** [comment]
Thank you for the review! :sunflower: 

Let me know if there are other blockers to merging that need my input. Typically I would assume a rebase, but I'm assuming that is not needed for this small doc change.

**Review by bhufmann — APPROVED** [review]
Looks good to me. Thanks!

**Pull request merged**
