### PR TITLE
Export DataTree to csv through FileDialogService

### PR DESCRIPTION
**Pull request by hriday-panchasara**
- Using Theia Backend to write files instead
- Users can choose file name/path in both browser & electron
- Show success/error message after

### CODE REVIEW

**Comment by hoangphamEclipse** [comment]
Thank you @hriday-panchasara for your review. I ran the code and found a few small issues:

1) When I have multiple traces opened and I tried to save the data tree view to a CSV file, there are multiple dialogs popped up (1 for each opened trace). I think you need to use the trace ID to determine which trace is in the current active tab. Please see the video below for more details. You see that right after I saved the CSV for the `apt` trace, another dialog popped up to ask me to save the CSV for the `64-bit` trace.

https://user-images.githubusercontent.com/92533264/224063658-2df801ac-85cd-4653-8ea0-73baa3f7eec5.mp4

2) I tried to save both files, and both files have the same content from `apt`. I think this issue will be resolved once you solved [1].

3) The content of the file contains some weird unit ` Âµs`. Please see the attached saved CSV file below. FYI, I am on Windows, maybe it is an OS encoding issue?
[apt.csv](https://github.com/eclipse-cdt-cloud/theia-trace-extension/files/10932914/apt.csv)

**Comment by hriday-panchasara** [comment]
> Thank you @hriday-panchasara for your review. I ran the code and found a few small issues:
> 
> 1. When I have multiple traces opened and I tried to save the data tree view to a CSV file, there are multiple dialogs popped up (1 for each opened trace). I think you need to use the trace ID to determine which trace is in the current active tab. Please see the video below for more details. You see that right after I saved the CSV for the `apt` trace, another dialog popped up to ask me to save the CSV for the `64-bit` trace.
> 
> 2. I tried to save both files, and both files have the same content from `apt`. I think this issue will be resolved once you solved [1].
> 3. The content of the file contains some weird unit ` Âµs`. Please see the attached saved CSV file below. FYI, I am on Windows, maybe it is an OS encoding issue?
>    [apt.csv](https://github.com/eclipse-cdt-cloud/theia-trace-extension/files/10932914/apt.csv)

Could you show me what your csv looks like for #3? I am using Numbers on Mac to open the attached csv and it looks identical to the Latency Statistics Table for this trace:
Screen Shot 2023-03-10 at 7 38 01 PM

**Comment by hoangphamEclipse** [comment]
> Could you show me what your csv looks like for 3? I am using Numbers on Mac to open the attached csv and it looks identical to the Latency Statistics Table for this trace:

Here's a screenshot of the CSV file opened in Excel. As you can see, some of the units are `Âµs`:

image

However, today I tried opening it with NotePad++ and it seems fine: 

image

**Comment by hriday-panchasara** [comment]
> 3\. µs

This issue is most likely due to a character encoding problem between Numbers and Excel. The character 'µ' is a non-ASCII character and its encoding can be handled differently by different software applications.

Numbers and Excel may be using different character encodings to interpret the text in the CSV file, causing the 'µ' character to be displayed differently in Excel than in Numbers. The 'Â' character that appears before the 'µ' character in Excel is likely a result of a character encoding error, where the 'µ' character is interpreted as two separate characters in the ISO-8859-1 encoding used by Excel. Numbers and LibreOffice use UTF-8 charset which is why this issue was noticed in those applications.

We can add the option to export statistics to .xls in the future, but for now here's how text/csv should be imported in Excel to ensure correct encoding and have header rows imported:

[Screen Recording 2023-03-14 at 4.19.54 PM.webm](https://user-images.githubusercontent.com/92893187/225139619-1f309143-cda8-44c0-9f8c-2267d5faf21f.webm)

**Comment by hriday-panchasara** [comment]
> > Could you show me what your csv looks like for 3? I am using Numbers on Mac to open the attached csv and it looks identical to the Latency Statistics Table for this trace:
> 
> Here's a screenshot of the CSV file opened in Excel. As you can see, some of the units are `Âµs`:
> 
> image
> 
> However, today I tried opening it with NotePad++ and it seems fine:
> 
> image

This issue is most likely due to a character encoding problem between Numbers and Excel. The character 'µ' is a non-ASCII character and its encoding can be handled differently by different software applications.

Numbers and Excel may be using different character encodings to interpret the text in the CSV file, causing the 'µ' character to be displayed differently in Excel than in Numbers. The 'Â' character that appears before the 'µ' character in Excel is likely a result of a character encoding error, where the 'µ' character is interpreted as two separate characters in the ISO-8859-1 encoding used by Excel. Numbers and LibreOffice use UTF-8 charset which is why this issue was noticed in those applications.

We can add the option to export statistics to .xls in the future, but for now here's how text/csv should be imported in Excel to ensure correct encoding and have header rows imported:

[Screen Recording 2023-03-14 at 4.19.54 PM.webm](https://user-images.githubusercontent.com/92893187/225139619-1f309143-cda8-44c0-9f8c-2267d5faf21f.webm)

**Review by hoangphamEclipse — APPROVED** [review]
Thank you for the detailed answers. If the issue regarding the unit is due to the fact that I did not import the file properly into Excel, then that is not a problem with the code. I re-tested the feature and it looks good to me.

**Comment by hoangphamEclipse** [comment]
> This issue is most likely due to a character encoding problem between Numbers and Excel. The character 'µ' is a non-ASCII character and its encoding can be handled differently by different software applications.
> 
> Numbers and Excel may be using different character encodings to interpret the text in the CSV file, causing the 'µ' character to be displayed differently in Excel than in Numbers. The 'Â' character that appears before the 'µ' character in Excel is likely a result of a character encoding error, where the 'µ' character is interpreted as two separate characters in the ISO-8859-1 encoding used by Excel. Numbers and LibreOffice use UTF-8 charset which is why this issue was noticed in those applications.
> 
> We can add the option to export statistics to .xls in the future,

@MatthewKhouzam should we backlog or document this somewhere? I don't know how useful it is. I think you can make the decision.

**Pull request merged**
