### PR TITLE
update to latest Theia community release: v1.49.1

### PR DESCRIPTION
**Pull request by bhufmann**
Update to Theia community release version 1.49.1

Signed-off-by: Bernd Hufmann <bernd.hufmann@ericsson.com>

### CODE REVIEW

**Comment by bhufmann** [comment]
Opening a trace from the File Explorer with right-mouse click on trace `Open With ... -> Trace Viewer` is not working anymore. Theia changed to use a quick pick menu and the Trace Viewer doesn't show up there. 

See https://github.com/eclipse-theia/theia/pull/13573 for the change. 

It needs to be investigated how to fix it on the trace extension side.

**Comment by bhufmann** [comment]
I noticed also that the progress message boxes are not shown (during start of trace server or opening a trace)

**Comment by bhufmann** [comment]
> I noticed also that the progress message boxes are not shown (during start of trace server or opening a trace)

This issue is also in master branch and not related by this upgrade patch.

**Comment by marcdumais-work** [comment]
IP ticket for the dependency that's failing the license check:
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/15475

**Review by marcdumais-work — APPROVED** [review]
LGTM - thanks Bernd!

I confirmed that the new code using the "openWithService" does the job, when opening a trace from the file navigator.

**Pull request merged**
