### PR TITLE
Update to latest Theia community release: v1.52.0

### PR DESCRIPTION
**Pull request by marcdumais-work**
This PR updates `@theia` extension `theia-traceviewer` so it uses the latest Theia community release (v1.52.0). Same for the browser and electron example applications in this repo. 

TODO:
- [x] investigate electron-rebuild problem (fixed)
- [x] Test Electron example

Note: there is a separate [PR](https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/1119) (#1119) to deal with the "open-with" no longer working with folders, since Theia 1.50.0 IIRC. We will probably want to merge that one too, before publishing a new version of `theia-traceviewer`. suitable for Theia 1.52.0 (latest community release)

### CODE REVIEW

**Comment by marcdumais-work** [comment]
IP Tickets for the new dependencies:

[main] INFO A review is required for npm/npmjs/-/app-builder-lib/24.13.3.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16244 .
[main] INFO A review is required for npm/npmjs/@ag-grid-community/react/32.2.0.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16245 .
[main] INFO A review is required for npm/npmjs/-/babel-loader/8.4.1.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16246 .
[main] INFO A review is required for npm/npmjs/-/playwright-core/1.47.2.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16247 .
[main] INFO A review is required for npm/npmjs/-/playwright/1.47.2.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16248 .
[main] INFO A review is required for npm/npmjs/@ag-grid-community/styles/32.2.0.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16249 .
[main] INFO A review is required for npm/npmjs/-/ag-charts-types/10.2.0.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16250 .
[main] INFO A review is required for npm/npmjs/@ag-grid-community/infinite-row-model/32.2.0.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16251 .
[main] INFO A review is required for npm/npmjs/-/eslint-module-utils/2.11.0.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16252 .
[main] INFO A review is required for npm/npmjs/-/envinfo/7.14.0.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16253 .
[main] INFO A review is required for npm/npmjs/@types/react/16.14.61.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16254 .
[main] INFO A review is required for npm/npmjs/-/electron-to-chromium/1.5.26.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16255 .
[main] INFO A review is required for npm/npmjs/@ag-grid-community/core/32.2.0.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16256 .
[main] INFO A review is required for npm/npmjs/@eslint-community/regexpp/4.11.1.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16257 .
[main] INFO A review is required for npm/npmjs/@playwright/test/1.47.2.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16258 .

**Review by bhufmann — APPROVED** [review]
Looks good to me! Thanks

**Review by bhufmann — APPROVED** [review]
Looks good to me. Thanks a lot for the upgrade!

**Review by bhufmann — APPROVED** [review]
Looks good to me. Thanks!

**Comment by marcdumais-work** [comment]
Thanks for the review!

**Pull request merged**
