### PR TITLE
Improve options menu styling

### LINKED ISSUE #751: Better Styling for Options Menu
The options menu in the abstract-output-component has a different look and feel than the rest of the application. It should be possible to css style it so that we can re-use the theia styles for it.

### PR DESCRIPTION
**Pull request by hriday-panchasara**
Change CSS style of options-menu so that we can re-use theia styles for it:
Screen Shot 2022-07-11 at 11 45 43 AM

Screen Shot 2022-07-11 at 11 45 20 AM

fixes #751

Signed-off-by: hriday-panchasara <hriday.panchasara@ericsson.com>

### CODE REVIEW

**Review by bhufmann — CHANGES_REQUESTED** [review]
The color of the trace viewer menus doesn't match the color of theia in light or dark theme. See for example the context sensitive menu of the file explorer or the main menu. Also, the context sensitive menu of the open traces menu doesn't match.  I think the menus should be all like the Theia menus.

image

image

image

**Comment by hoangphamEclipse** [comment]
Hi Hriday, I also tried your patch and in addition to Bernd's comment, I found that the style of the options menu of individual output views should also be changed to match Theia's theme.

image

**Comment by hriday-panchasara** [comment]
Changed options menu style to match Theia's theme:
Screen Shot 2022-08-05 at 4 37 45 PM

**Review by hoangphamEclipse — APPROVED** [review]
I tested the code and it looks good to me.

**Review by bhufmann — APPROVED** [review]
Looks good to me. Thanks!

**Pull request merged**
