### PR TITLE
Uplift theia dependencies from v1.34.2 to 1.37.2

### PR DESCRIPTION
**Pull request by marco-miller**
Do a `yarn upgrade` prior.
- This `upgrade` is necessary so the following Theia version uplift still works with the electron yarn commands.
- This resulting `yarn.lock` is then based on going from clean to having run `yarn` locally a few times.

Base this uplifted-to Theia version on [community's latest](https://theia-ide.org/releases/).

Add a clarifying step in README so the yarn commands work locally.
- Fix the `rebuild:browser` scripting so it works with this and versus electron's.
  
Cap the `fontawesome-svg-core` version to less than `1.3.0`.
- Without this change, the hereby `upgrade` leads to a broken `yarn` build.
- This is despite requesting for a version that remains compatible with `1.2.17`.
- So a `yarn upgrade` without this adjustment lends the use of `v1.3.0`, which breaks the build.
- Below [1] flags that breaking version as deprecated, and the later versions are way more major uplifts (`6.x.y`).

[1]https://www.npmjs.com/package/@fortawesome/fontawesome-svg-core?activeTab=versions

Signed-off-by: Marco Miller <marco.miller@ericsson.com>

### CODE REVIEW

**Review by bhufmann — CHANGES_REQUESTED** [review]
Could you please upgrade to the latest community release [1] done May 05, 2023, i.e. 1.37.x? This will be the baseline used in the next CDT cloud blueprint community release as well. Thanks.

[1] https://theia-ide.org/releases/

**Comment by marco-miller** [comment]
> Could you please upgrade to the latest community release [1] done May 05, 2023, i.e. 1.37.x? This will be the baseline used in the next CDT cloud blueprint community release as well. Thanks.
> 
> [1] https://theia-ide.org/releases/

The latest that I saw flying by is `1.38.0`, publicised on Twitter IIRC. Maybe [1] above wasn't updated yet accordingly? But I might be misunderstanding this process. I can drop commit d2a4745 (`1.38.0`) and stick to `1.37.2` (current 1.37 latest), commit 08770d7, no problem.

A note, I'm working on fixing a `rebuild` issue with `electron`, pertaining to `node-abi` not being up-to-date it seems. So I'll amend some of these commits soon as well for that.

**Comment by bhufmann** [comment]
> The latest that I saw flying by is `1.38.0`, publicised on Twitter IIRC. Maybe [1] above wasn't updated yet accordingly?

The reference [1] is about community releases (every 3 month) and the content is correct. It has a cross-reference to the monthly releases on top if the page.

**Comment by marco-miller** [comment]
As previously mentioned, I get the below error upon testing this PR with `electron`. @vince-fugnitto, would you know why, by any chance? Not sure if I should upgrade anything or not, as I think the dependency versions already match with Theia's currently. But WDYT?

```
~/git/theia-trace-extension$ yarn start:electron
yarn run v1.22.19
$ yarn rebuild:electron && yarn --cwd examples/electron start
$ yarn --cwd examples/electron theia rebuild:electron --cacheRoot ../..
$ /home/(...)/git/theia-trace-extension/node_modules/.bin/theia rebuild:electron --cacheRoot ../..
Module not found: find-git-repositories
Processed "node-pty"
Processed "nsfw"
Processed "drivelist"
Processed "native-keymap"
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
Could not detect abi for version 23.3.5 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
```

**Comment by vince-fugnitto** [comment]
@marco-miller it may be time to perform a general `yarn upgrade` to update the lockfile, after doing so the `yarn rebuild:electron` command passed. Please note that there might  be other changes necessary after performing the upgrade (ex: `fortawesome`).

**Review by bhufmann — COMMENTED** [review]
I build the electron app (in examples/electron, yarn package) and when I run it afterwards I get the following print-out and the app doesn't start:
```
./Theia\ Trace\ Example\ Application-0.1.0.AppImage 
/tmp/.mount_Theia 7E2hPf/resources/app/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: Module did not self-register: '/tmp/.mount_Theia 7E2hPf/resources/app/node_modules/drivelist/build/Release/drivelist.node'.
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1259:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at bindings (/tmp/.mount_Theia 7E2hPf/resources/app/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/tmp/.mount_Theia 7E2hPf/resources/app/node_modules/drivelist/js/index.js:25:27) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.12.1

```

Do you get the same thing?

**Comment by vince-fugnitto** [comment]
@bhufmann it works well for me, can you try with a compatible node version as I don't believe `node 18` is supported by the framework according to the [prerequisites](https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites).

**Comment by marco-miller** [comment]
Now, trying to `start` the `browser` example after packaging `electron` fails with a similar issue. But it works after cleaning and rebuilding without packaging `electron` prior. And I just noticed other versions under `examples/electron` which I might have to bump too, accordingly (e.g., `electronVersion`); WIP.

**Comment by marco-miller** [comment]
> Now, trying to `start` the `browser` example after packaging `electron` fails with a similar issue. But it works after cleaning and rebuilding without packaging `electron` prior. And I just noticed other versions under `examples/electron` which I might have to bump too, accordingly (e.g., `electronVersion`); WIP.

-Done; pushed by now. I also added a related note in the README.

**Review by bhufmann — COMMENTED** [review]
I'm using v16.20.0 as well. I did `git clean -xdf`, and I still get the issue. Deleting the `node_modules` directory doesn't help for me. Any suggestions?

**Comment by marco-miller** [comment]
> I'm using v16.20.0 as well. I did `git clean -xdf`, and I still get the issue. Deleting the `node_modules` directory doesn't help for me. Any suggestions?

Are you using the latest PR update with the now aligned `electronVersion`? If so, maybe share your exact sequence of terminal commands, so I can try to reproduce it. Thanks.

**Comment by bhufmann** [comment]
> > I'm using v16.20.0 as well. I did `git clean -xdf`, and I still get the issue. Deleting the `node_modules` directory doesn't help for me. Any suggestions?
> 
> Are you using the latest PR update with the now aligned `electronVersion`? If so, maybe share your exact sequence of terminal commands, so I can try to reproduce it. Thanks.

I had to clean my environment and now it's working with both the executable and `yarn start:electron`. Btw, I didn't have to delete the node-modules directory after `yarn package` and it still works for both.

**Comment by marco-miller** [comment]
> > > I'm using v16.20.0 as well. I did `git clean -xdf`, and I still get the issue. Deleting the `node_modules` directory doesn't help for me. Any suggestions?
> > 
> > Are you using the latest PR update with the now aligned `electronVersion`? If so, maybe share your exact sequence of terminal commands, so I can try to reproduce it. Thanks.
> 
> I had to clean my environment and now it's working with both the executable and `yarn start:electron`. Btw, I didn't have to delete the node-modules directory after `yarn package` and it still works for both.
> 
> I had to delete the node-modules directory for `yarn start:browser`. It would be good to have that fixed too.

The latter is what I mentioned in the README, yes. I don't know how to fix this further, thus that note I added up in there.

**Comment by marco-miller** [comment]
> When running `yarn package` I get the error print-out below. However, the executable still works. Do you get the same error?
> 
> ```
>     Error: Could not detect abi for version 23.3.6 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
>         at getAbi (/home/eedbhu/git/theia-training/theia-trace-extension/node_modules/node-abi/index.js:36:9)
>         at module.exports (/home/eedbhu/git/theia-training/theia-trace-extension/node_modules/prebuild-install/rc.js:73:57)
>         at Object.<anonymous> (/home/eedbhu/git/theia-training/theia-trace-extension/node_modules/prebuild-install/bin.js:9:25)
>         at Module._compile (node:internal/modules/cjs/loader:1196:14)
>         at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
>         at Module.load (node:internal/modules/cjs/loader:1074:32)
>         at Function.Module._load (node:internal/modules/cjs/loader:909:12)
>         at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
>         at node:internal/main/run_main_module:22:47
> ```

This was previously fixed for me locally when I updated this PR with that other commit, about the clean yarn (re)upgrade &co.

**Comment by bhufmann** [comment]
> > When running `yarn package` I get the error print-out below. However, the executable still works. Do you get the same error?
> > ```
> >     Error: Could not detect abi for version 23.3.6 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
> >         at getAbi (/home/eedbhu/git/theia-training/theia-trace-extension/node_modules/node-abi/index.js:36:9)
> >         at module.exports (/home/eedbhu/git/theia-training/theia-trace-extension/node_modules/prebuild-install/rc.js:73:57)
> >         at Object.<anonymous> (/home/eedbhu/git/theia-training/theia-trace-extension/node_modules/prebuild-install/bin.js:9:25)
> >         at Module._compile (node:internal/modules/cjs/loader:1196:14)
> >         at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
> >         at Module.load (node:internal/modules/cjs/loader:1074:32)
> >         at Function.Module._load (node:internal/modules/cjs/loader:909:12)
> >         at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
> >         at node:internal/main/run_main_module:22:47
> > ```
> 
> This was previously fixed for me locally when I updated this PR with that other commit, about the clean yarn (re)upgrade &co.

That doesn't fix it for me.

**Comment by marco-miller** [comment]
> > > When running `yarn package` I get the error print-out below. However, the executable still works. Do you get the same error?
> > > ```
> > >     Error: Could not detect abi for version 23.3.6 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
> > >         at getAbi (/home/eedbhu/git/theia-training/theia-trace-extension/node_modules/node-abi/index.js:36:9)
> > >         at module.exports (/home/eedbhu/git/theia-training/theia-trace-extension/node_modules/prebuild-install/rc.js:73:57)
> > >         at Object.<anonymous> (/home/eedbhu/git/theia-training/theia-trace-extension/node_modules/prebuild-install/bin.js:9:25)
> > >         at Module._compile (node:internal/modules/cjs/loader:1196:14)
> > >         at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
> > >         at Module.load (node:internal/modules/cjs/loader:1074:32)
> > >         at Function.Module._load (node:internal/modules/cjs/loader:909:12)
> > >         at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
> > >         at node:internal/main/run_main_module:22:47
> > > ```
> > 
> > 
> > This was previously fixed for me locally when I updated this PR with that other commit, about the clean yarn (re)upgrade &co.
> 
> That doesn't fix it for me.

@vince-fugnitto, would you be able to also review this (updated) PR again at this stage? So we may confirm issues with it if any left. I'm able to build it locally but @bhufmann cannot. I'd need your help if any (issues), or from someone in your team please, to progress on this -if anything more. Thanks.

**Comment by vince-fugnitto** [comment]
@marco-miller @bhufmann I followed some configurations and dependencies used in [theia-blueprint](https://github.com/eclipse-theia/theia-blueprint) (as it is the main example the project has for using and packaging electron) and it seems to work better.

image

I am able to start the browser example, start the electron example, package electron and there are no longer errors about the `node-abi`:

```
$ (cd examples/electron/ && yarn package)
/home/vince/workspaces/theia-trace-extension/examples/electron
yarn run v1.22.19
$ electron-builder
  • electron-builder  version=23.6.0 os=5.15.0-69-generic
  • loaded configuration  file=/home/vince/workspaces/theia-trace-extension/examples/electron/electron-builder.yml
  • description is missed in the package.json  appPackageFile=/home/vince/workspaces/theia-trace-extension/examples/electron/package.json
  • writing effective config  file=dist/builder-effective-config.yaml
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=linux arch=x64 electron=23.3.6 appOutDir=dist/linux-unpacked
  • copying Electron  source=/home/vince/workspaces/theia-trace-extension/node_modules/electron/dist destination=/home/vince/workspaces/theia-trace-extension/examples/electron/dist/linux-unpacked
  • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
  • file source doesn't exist  from=/home/vince/workspaces/theia-trace-extension/examples/electron/plugins
  • file source doesn't exist  from=/home/vince/workspaces/theia-trace-extension/trace-compass-server
  • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
  • building        target=AppImage arch=x64 file=dist/Theia Trace Example Application-0.1.0.AppImage
  • default Electron icon is used  reason=application icon is not set
  • building        target=deb arch=x64 file=dist/electron-theia-trace-example-app_0.1.0_amd64.deb
Done in 131.66s.
```

For reference this is their [electron-builder.yml](https://github.com/eclipse-theia/theia-blueprint/blob/master/applications/electron/electron-builder.yml).

**Comment by marco-miller** [comment]
> @marco-miller @bhufmann I followed some configurations and dependencies used in [theia-blueprint](https://github.com/eclipse-theia/theia-blueprint) (as it is the main example the project has for using and packaging electron) and it seems to work better.
> 
> image
> 
> I am able to start the browser example, start the electron example, package electron and there are no longer errors about the `node-abi`:
> 
> ```
> $ (cd examples/electron/ && yarn package)
> /home/vince/workspaces/theia-trace-extension/examples/electron
> yarn run v1.22.19
> $ electron-builder
>   • electron-builder  version=23.6.0 os=5.15.0-69-generic
>   • loaded configuration  file=/home/vince/workspaces/theia-trace-extension/examples/electron/electron-builder.yml
>   • description is missed in the package.json  appPackageFile=/home/vince/workspaces/theia-trace-extension/examples/electron/package.json
>   • writing effective config  file=dist/builder-effective-config.yaml
>   • skipped dependencies rebuild  reason=npmRebuild is set to false
>   • packaging       platform=linux arch=x64 electron=23.3.6 appOutDir=dist/linux-unpacked
>   • copying Electron  source=/home/vince/workspaces/theia-trace-extension/node_modules/electron/dist destination=/home/vince/workspaces/theia-trace-extension/examples/electron/dist/linux-unpacked
>   • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
>   • file source doesn't exist  from=/home/vince/workspaces/theia-trace-extension/examples/electron/plugins
>   • file source doesn't exist  from=/home/vince/workspaces/theia-trace-extension/trace-compass-server
>   • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
>   • building        target=AppImage arch=x64 file=dist/Theia Trace Example Application-0.1.0.AppImage
>   • default Electron icon is used  reason=application icon is not set
>   • building        target=deb arch=x64 file=dist/electron-theia-trace-example-app_0.1.0_amd64.deb
> Done in 131.66s.
> ```
> 
> For reference this is their [electron-builder.yml](https://github.com/eclipse-theia/theia-blueprint/blob/master/applications/electron/electron-builder.yml).

Many thanks for having checked this and the tips. I'll look into these and likely push an update soon.

**Comment by bhufmann** [comment]
The errors during build are gone with these suggested changes. However, I get the error about `ERR_DLOPEN_FAILED` from above. I did the following steps:
```
git clean -xdf 
yarn
cd examples/electron/
yarn package
cd dist/
./Theia\ Trace\ Example\ Application-0.1.0.AppImage 
```

Then I noticed if I do `yarn start:electron` first before `yarn package` I don't get the error. @vince-fugnitto, `yarn start:browser` does `rebuild:electron (yarn --cwd examples/electron theia rebuild:electron --cacheRoot ../..)`. Should that be done as well before package?

**Comment by vince-fugnitto** [comment]
@bhufmann these are the steps I do generally:

- `git clean -ffdx`
- `yarn`
- `cd examples/electron`
- `yarn theia rebuild:electron`
- `yarn package`
- `cd dist/`
- `./Theia\ Trace\ Example\ Application-0.1.0.AppImage`

**Comment by bhufmann** [comment]
> @bhufmann these are the steps I do generally (when packaging):
> 
> * `git clean -ffdx`
> * `yarn`
> * `cd examples/electron`
> * `yarn theia rebuild:electron`
> * `yarn package`
> * `cd dist/`
> * `./Theia\ Trace\ Example\ Application-0.1.0.AppImage`

Thanks for the steps. I've never had to do step `yarn theia rebuild:electron`. Maybe this should be added to the package step, so that user don't forget and run into the same issue?

**Comment by marco-miller** [comment]
I get `ERR_DLOPEN_FAILED` when using `yarn start:browser` after having used the electron yarn commands above. It works after git-cleaning again along with `yarn`. I mean, all this after having applied the previous fixes locally. Anyway, I'll push them now while updating the README so it mentions git-cleaning where necessary, AFAIK that is. This PR will then be ready for review again.

**Comment by vince-fugnitto** [comment]
@marco-miller @bhufmann so you are aware the current `yarn theia rebuild:electron` and `yarn rebuild:browser` scripts that you have in the repository rebuilds native modules, and you call them at the moment when performing `yarn start:browser` and `yarn start:electron`:

https://github.com/eclipse-cdt-cloud/theia-trace-extension/blob/45432b4055d63022aa68676b30aa61e07b2c28b6/package.json#L13-L14

It is important when switching from the browser application to the electron application (and vice-versa) to rebuild for the target, no need to `git clean -ffdx` and so on.

For packaging this will also be required which is why I mentioned it in https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/984#issuecomment-1587744405.

**Comment by marco-miller** [comment]
> @marco-miller @bhufmann so you are aware the current `yarn theia rebuild:electron` and `yarn rebuild:browser` scripts that you have in the repository rebuilds native modules, and you call them at the moment when performing `yarn start:browser` and `yarn start:electron`:
> 
> https://github.com/eclipse-cdt-cloud/theia-trace-extension/blob/45432b4055d63022aa68676b30aa61e07b2c28b6/package.json#L13-L14
> 
> It is important when switching from the browser application to the electron application (and vice-versa) to rebuild for the target, no need to `git clean -ffdx` and so on.
> 
> For packaging this will also be required which is why I mentioned it in [#984 (comment)](https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/984#issuecomment-1587744405).

Ah, ok; thanks for having clarified that even further. I'll update this accordingly. I'd have this question please: is it normal that the `rebuild:browser` script doesn't `--cdw` to `examples/browser` first, as `rebuild:electron` does for its own? As for the `--cacheRoot` difference though, it looks genuine to me.

**Comment by marco-miller** [comment]
> > > @marco-miller @bhufmann so you are aware the current `yarn theia rebuild:electron` and `yarn rebuild:browser` scripts that you have in the repository rebuilds native modules, and you call them at the moment when performing `yarn start:browser` and `yarn start:electron`:
> > > https://github.com/eclipse-cdt-cloud/theia-trace-extension/blob/45432b4055d63022aa68676b30aa61e07b2c28b6/package.json#L13-L14
> > > 
> > > It is important when switching from the browser application to the electron application (and vice-versa) to rebuild for the target, no need to `git clean -ffdx` and so on.
> > > For packaging this will also be required which is why I mentioned it in [#984 (comment)](https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/984#issuecomment-1587744405).
> > 
> > 
> > Ah, ok; thanks for having clarified that even further. I'll update this accordingly. I'd have this question please: is it normal that the `rebuild:browser` script doesn't `--cdw` to `examples/browser` first, as `rebuild:electron` does for its own? As for the `--cacheRoot` difference though, it looks genuine to me.
> 
> I think that is the issue for the `:browser` case. So I'm currently looking into aligning the `rebuild:browser` script.

I'm done pushing my latest fixes/update, ready for review again. Thanks for all the hints that led to this so far.

**Review by bhufmann — APPROVED** [review]
Thanks. It also works following the steps in the README.md for packaging. You could do the rebuilding of electron as part of the script `yarn package`.

**Comment by marco-miller** [comment]
> Thanks. It also works following the steps in the README.md for packaging. You could do the rebuilding of electron as part of the script `yarn package`.

Yes; pushed as a follow-up commit herein. Thanks.

**Review by bhufmann — APPROVED** [review]
Looks good to me. Thanks for the upgrade!

**Pull request merged**
